### ISSUE TITLE
No Output for Droplets, Images, etc

### ISSUE THREAD

**Issue by maestrofx** [HeadTalker/digitalocean-dashboard#4]
Hi there,

I has no output when open it in browser. All the droplets, images, domains, etc.
When I run :
`$ curl -X GET -H "Content-Type: application/json" -H "Authorization: Bearer MY_API_TOKEN" "https://api.digitalocean.com/v2/droplets?page=1&per_page=1`

it works well.

Please, kind of helps.
Thank you.

**Comment by HeadTalker** [comment]
Hi,

Do you have PHP CURL libraries installed?  It is a different package then the command line CURL.

**Comment by maestrofx** [comment]
Hi,

I was playing with the codes and yes, found that was caused by the dependency libraries. But it doesn't work too. Till spending more times to check what I've modified and deciding to re-clone it, it works!

Thank you.

**Comment by HeadTalker** [comment]
Glad to hear.

:+1:
